server:
  port: 8080
spring:
  application:
    name: peanut_takeaway
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/peanut?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: Wahson11736
  # redis配置虚拟机
  redis:
    host: 192.168.72.128
    port: 6379
    password: 123456
    database: 0
  cache:
    redis:
      # 缓存有效期，单位 ms, 30分钟
      time-to-live: 1800000

mybatis-plus:
  configuration:
    # 在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

peanut:
#  path: D:\peanut_takeaway\ 菜品 套餐图片
  path: F:\MyCode\person_project\peanut_takeaway\peanut_takeaway\src\main\resources\static\backend\images\dish\
